name: Install npm packages
description: Installs npm packages and manages its cache

env:
  NODE_VERSION: 22.9.0
  PNPM_VERSION: 9.15.1

runs:
  using: composite
  steps:
    # https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - name: Setup Node.js v${{ env.NODE_VERSION }} with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "pnpm"

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
