name: Labeler

on: pull_request_target

jobs:
  labeler:
    name: Label
    permissions:
      contents: read
      pull-requests: write

    runs-on: self-hosted

    steps:
      - name: Add labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
